[wokwi]
version = 1
firmware = '../.pio/build/esp32doit-devkit-v1/firmware.bin' # Adjust path as needed
elf = '../.pio/build/esp32doit-devkit-v1/firmware.elf' # Adjust path as needed
gdbServerPort=3333